# Generated by Django 3.2.15 on 2022-10-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20220930_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='comment',
            field=models.CharField(default='a lovely broom', max_length=256),
            preserve_default=False,
        ),
    ]
