# Generated by Django 3.2.15 on 2022-10-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_listings_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.auction_listings'),
        ),
    ]
