# Generated by Django 3.2.15 on 2022-10-04 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_comments_listing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='watchlist',
            new_name='watchlists',
        ),
    ]
