# Generated by Django 3.2.15 on 2022-10-05 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bids_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='listing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
