# Generated by Django 3.2.15 on 2022-10-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20221005_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
